version: "3.8"

services:
  mongodb:
    image: mongo:4.1
    container_name: webprotege-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - webprotege_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  webprotege:
    image: webprotege-custom
    container_name: webprotege
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - webprotege.mongodb.host=mongodb
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - webprotege.application.version=4.0.7
    volumes:
      - webprotege_data:/data/webprotege
    ports:
      - "5000:8080"
    networks:
      - webprotege_network

volumes:
  mongodb_data:
  webprotege_data:

networks:
  webprotege_network:
    driver: bridge

